config/routes.rb
Vsol::Application.routes.draw do
  get "mails/list" => "smails#list"
  get '/login', to: "sessions#new"
  get "mails/send/:id" => "smails#delay_mail", as: 'mails/send'
  delete 'logout' => "sessions#destroy"
  post '/login', to: "sessions#create"
  get '/signup', to: "users#new"
  get '/sand', to: "sessions#sandbox"
  get '/auth/:provider/callback', to: 'sessions#create_social'
  get 'tsecret', to: "static_pages#top_secret"

  DelayedJobWeb.use Rack::Auth::Basic do |username, password|
    username == ENV['DJ_USER'] && password == ENV['DJ_PASS']
    end
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  resources :users
  resources :smails
  resources :account_activations, only: [:edit]

  root "static_pages#home"

  

end

app/models/smail.rb
class Smail < ActiveRecord::Base
  validates :message, presence: true
  validates :scheduled_at, presence: true
end

app/controllers/smails_controller.rb
class SmailsController < ApplicationController
  before_action :is_admin

  NewsletterJob = Struct.new(:users, :message) do
    def perform
      users.each do |user|
        @user = user
        UserMailer.scheduled(user, message).deliver
      end
    end
  end

  def new
    @title = "NewMail"
    @smail = Smail.new
  end

  def show
    @title = "Mail Task"
    @smail = Smail.find(params[:id])
  end

  def list
    @title = "Mails"
    @smails = Smail.order(:scheduled_at).all
  end

  def create
    @smail = Smail.new(smail_params)
    if @smail.save
      flash[:info] = "New mail created."
      redirect_to(mails_list_url)
    else
      render 'new'
    end
  end

  def update
    @smail = Smail.find(params[:id])
    if @smail.update_attributes(smail_params)
      flash[:success] = "Task updated"
      # redirect_to (mails_list_url)
      redirect_to(mails_list_url)
    else
      render 'show'
    end
  end

  def destroy
    Smail.find(params[:id]).destroy
    flash[:success] = "Mail task deleted"
    redirect_to(mails_list_url)
  end

  def delay_mail
    users = User.first(3)
    id = params[:id]
    mail = Smail.find(id)
    message = mail.message
    time = mail.scheduled_at
    Delayed::Job.enqueue NewsletterJob.new(users, message), 0, time
    mail.update_attribute :enqueued, true
    redirect_to(mails_list_url)
  end

  private

  def smail_params
    params.require(:smail).permit(:message, :scheduled_at)
  end

  def is_admin
    redirect_to(root_url) unless current_user.admin?
  end
end

app/views/smails/_smails.html.erb
<% @smails.each do |smail| %>
  <tr>
    <th>
      <% if smail.enqueued %>
          <%= smail.id %>
      <% else %>
          <%= link_to smail.id, smail_path(smail.id), method: :get %> </th>
      <% end %>
    <td> <%= smail.message %> </td>
    <td> <%= smail.scheduled_at %> </td>
    <td> <%= link_to "delete", smail_path(smail.id), method: :delete, data: { confirm: "You sure?" } %> </td>
    <td>
      <% if smail.enqueued %>
          enqueued
      <% else %>
          <%= link_to "send to queue", mails_send_path(smail.id), method: :get, data: { confirm: "You sure?" } %>
      <% end %>
        </td>
  </tr>
<% end %>

app/views/smails/list.html.erb
<h1>Mail Tasks List</h1>
<table class="table">
  <thead>
  <tr>
    <th scope="col">id</th>
    <th scope="col">message</th>
    <th scope="col">scheduled_at</th>
    <th scope="col"> </th>
    <th scope="col"> </th>
  </tr>
  </thead>
  <tbody>
  <%= render "smails" %>
  </tbody>
</table>
<div class="row">
  <div class="col-md-3">
    <%= link_to "New Mail", new_smail_path, class: "btn btn-lg btn-primary" %>
  </div>
  <div class="col-md-7">
  </div>
  <div class="col-md-2 justify-content-end">
    <%= link_to "Manage queue", '/delayed_job', method: :get, class: "btn btn-lg btn-success " %>
  </div>
</div>

app/views/smails/new.html.erb
<h1>New Mail Task</h1>
<%= render 'shared/smail_error_messages' %>
<%= form_for(@smail, :html => {:class => 'form-signin text-center'}) do |f| %>
  <%= f.label :message, class: 'sr-only' %>
  <%= f.text_area :message, class: 'form-control', placeholder: 'Message body' %><br>
  <div class="form-group">
    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
      <input type="text" name="smail[scheduled_at]" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
      <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>
  </div>
  <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>

app/views/smails/show.html.erb
<h1>Mail Task</h1>
<%#= render 'shared/smail_error_messages' %>
<%= form_for(@smail, :html => {:class => 'form-signin text-center'}) do |f| %>
  <%= f.label :message, class: 'sr-only' %>
  <%= f.text_area :message, class: 'form-control', placeholder: 'Message body' %><br>
  <div class="form-group">
    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
      <input type="text" name="smail[scheduled_at]" class="form-control datetimepicker-input" data-target="#datetimepicker1" value="<%= @smail.scheduled_at %>"/>
      <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>
  </div>
  <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({
            format: 'YYYY-MM-DD HH:mm:ss'
        });
    });
</script>