config/routes.rb
Vsol::Application.routes.draw do
  get "mails/list" => "smails#list"
  get '/login', to: "sessions#new"
  get "mails/send/:id" => "smails#delay_mail", as: 'mails/send'
  delete 'logout' => "sessions#destroy"
  post '/login', to: "sessions#create"
  get '/signup', to: "users#new"
  get '/sand', to: "sessions#sandbox"
  get '/auth/:provider/callback', to: 'sessions#create_social'
  get 'tsecret', to: "static_pages#top_secret"

  DelayedJobWeb.use Rack::Auth::Basic do |username, password|
    username == ENV['DJ_USER'] && password == ENV['DJ_PASS']
    end
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]

  resources :users
  resources :smails
  resources :account_activations, only: [:edit]

  root "static_pages#home"

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container col-md-12">
    <div class="row" style="padding: 0 16px">
      <div class="col-md-3">

      </div>
      <div class="col-md-8"></div>
      <div class="col-md-1">
        <span class="text-muted"><small>SidLab</small></span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" id="logo" href="/">UsrCtrl</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="col-md-1"></div>
    <div class="collapse navbar-collapse col-md-10 justify-content-end" id="navbarCollapse">
      <ul class="navbar-nav">
        <li class="nav-item
          <% if @title == "Home" %>active
          <% end %>">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item
          <% if @title == "Top Secret" %>active
          <% end %>">
          <a class="nav-link" href="<%= tsecret_path %>">Top Secret</a>
        </li>
        <% if !logged_in? && !social_user %>
          <li class="nav-item
          <% if @title == "SignUp" %>active
          <% end %>">
            <a class="nav-link" href="<%= signup_path %>">SignUp</a>
          </li>
          <li class="nav-item
          <% if @title == "Login" %>active
          <% end %>">
            <a class="nav-link" href="<%= login_path %>">Login</a>
          </li>
        <% elsif logged_in? %>
          <li class="nav-item
                  <% if @title == "Profile" %>active
                  <% end %>">
            <a class="nav-link" href="<%= user_path(current_user.id) %>">Profile</a>
          </li>
          <li class="nav-item
            <% if @title == "Logout" %>active
            <% end %>">
            <a class="nav-link" href="<%= logout_path %>" data-method="delete">Logout</a>
          </li>
          <li class="orange">
            <span class="glyphicon glyphicon-user"></span><%= current_user.email %>
          </li>
        <% elsif social_user %>
          <li class="orange">
            <i class="fa fa-<%= session[:social_icon] %>"></i>&nbsp;<%= social_user %>
          </li>
          <li class="nav-item
            <% if @title == "Logout" %>active
            <% end %>">
            <a class="nav-link" href="<%= logout_path %>" data-method="delete">Logout</a>
          </li>

        <% end %>

        <% if is_admin? %>
          <li class="nav-item dropdown
                  <% if @title == "Users" %>active
                  <% end %>">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Admin
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="<%= users_path %>">Users</a>
              <a class="dropdown-item" href="<%= mails_list_path %>">Mails</a>
            </div>
          </li>
        <% end %>


      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="favicon.ico">
  <title><%= full_title (@title) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Custom styles for this template -->
  <script src="https://use.fontawesome.com/57c7a1a3fd.js"></script>
</head>

<body>

<%= render "layouts/header" %>

<!-- Begin page content -->
<main class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%#= debug(params) if Rails.env.development? %>

</main>

<%= render "layouts/footer" %>


</body>
</html>